version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/mongo_db


  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit_mq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq_storage

  volumes:
    mongodbdata:
    rabbitmqdata:
